BankCharge/Models/Bank.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BankCharge.Models
{
    public class Bank
    {
        public int BankId { get; set; }
        public string Name { get; set; }

      
        public string Image { get; set; }
       
        public IFormFile ImageUrl { get; set; }
        public int Charge { get; set; }
        public string CardType { get; set; }
      

    }
}

BankCharge/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankCharge.Models;
using BankCharge.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BankCharge.Controllers
{
    
    [Authorize]
    [Route("[controller]/[action]")]
    public class BankController : Controller
    {
        private readonly IBankService _bankService;
       
        private readonly IFileService _fileService;
        private readonly IPatnerService _patnerService;

        //private IHostingEnvironment _env;
        public BankController(IBankService bankService, IFileService fileService, IPatnerService patnerService)
        {
            _bankService = bankService;
            _fileService = fileService;
            _patnerService = patnerService;
            //_env = env;
        }
        [HttpGet]
        public IActionResult Index(int id)
        {
            var bank = _bankService.GetBanks();
            foreach (var item in bank)
            {
                item.Image = "/Image/" + item.Image;
               
            }
            return View(bank);
        }

        [HttpGet]
        public IActionResult New()
        {


            ViewBag.BankName = _bankService.GetBanks();
            return View();
        }

        [HttpPost]
        public JsonResult New(List<Bank> banks)
        {
            try
            {
                foreach (var item in banks)
                {
                    
                    _fileService.SavaImage(item.ImageUrl);
                    item.Image = item.ImageUrl.FileName;
                  
                    
                    _bankService.New(item);

                }
                return Json(banks);
            }
            catch (Exception e)
            {

                throw e;
            }

        }
        [HttpGet]
        public IActionResult EditBank([FromQuery]int id)
        {
          
            if (id == 0)
            {
                return NotFound();
            }
           
            Bank bank = _bankService.GetBankById(id);
            bank.Image = "/Image/" + bank.Image;
            if (bank == null)
                return NotFound();
            return View(bank);
        }

        [HttpPost]
        public IActionResult EditBank(Bank bank)
        {
            if (bank.BankId != bank.BankId)
                return NotFound();

            if (ModelState.IsValid)
            {
                if (bank.ImageUrl == null)
                {
                    bank.Image = default;
                }
                else
                {
                    _fileService.SavaImage(bank.ImageUrl);
                    bank.Image = bank.ImageUrl.FileName;
                }
                    _bankService.EditBank(bank);
                return RedirectToAction("Index");
            }
            return View(bank);
        }
        public IActionResult DeleteBank(int id)
        {
            Bank bank = _bankService.GetBankById(id);
            if (bank == null)
            {
                return NotFound();
            }

            return View(bank);
        }
        [HttpPost]
        public IActionResult DeleteBank(int BankId, Bank bank)
        {
            if (_bankService.DeleteBank(BankId) > 0)
            {
                return RedirectToAction("Index");
            }
            return View(bank);
        }

        [HttpPost]
        public JsonResult Search(string txtValue)
        {
            var bank = _bankService.GetBankSearch(txtValue);
            return Json(bank);
        }
    }
}

BankCharge/Views/Bank/DeleteBank.cshtml
@model BankCharge.Models.Bank
@{
    ViewData["Title"] = "DeleteBank";
}

<h3 class="alert">Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BankId)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Charge)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Charge)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CardType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CardType)
        </dd>
        

    </dl>
    <form asp-action="DeleteBank" asp-controller="Bank" method="post">
        <input type="hidden" asp-for="BankId" />
        <input type="submit" value="YES" class="btn btn-danger btn-sm" /> <a href="/Bank/Index" class="btn btn-danger">NO</a>
    </form>
</div>

BankCharge/Views/Bank/EditBank.cshtml
@model BankCharge.Models.Bank
@{
    ViewData["Title"] = "EditBank";
}

<section class="content-header">
    <section>
        <h2>Edit Bank</h2>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="EditBank" asp-controller="Bank" method="post">
                    <input type="hidden" name="BankId" value="@Model.BankId" />
                    <div class="form-group">


                        <label class="control-label">Bank Name</label>
                        <input name="Name" value="@Model.Name" class="form-control" required />
                    </div>
                    <div>
                        <img class="img-responsive" src="@Model.Image" alt="sala image aayena" height="50" width="50" style="border-radius:50%" />
                        <input type="file" name="ImageUrl" id="img" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Charge</label>
                        <input type="number" name="Charge" value="@Model.Charge" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Card Type</label><br />
                        <select class="js-example-basic-multiple" name="CardType" multiple="multiple" style="width :360px">
                           
                            <option value="MasterCard">MasterCard</option>
                            <option value="STC">STC </option>
                            <option value="Visa">Visa </option>
                        </select>
                    </div>



                    <div class="form-group">
                        <input type="submit" value="EditBank" class="btn btn-success btn-sm" />
                    </div>
                </form>
            </div>
        </div>

    </section>
</section>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
</script>

BankCharge/Views/Bank/Index.cshtml
@model IEnumerable<BankCharge.Models.Bank>
@{
    ViewData["Title"] = "Index";
}

<section class="content-header">
    <h1>
        Bank

    </h1>
</section>

<section>
    <h4 align="right">
        <a href="/Bank/New"><i class="fa fa-plus-square" aria-hidden="true">Add Bank</i> </a>
    </h4>
    <div>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
        <br />

        <br />
        <table class="table table-responsive table-striped table-bordered table-hover table-condensed " id="mytable">
            <thead>
                <tr style="background-color:cadetblue">
                    <th style="width:200px; ">Bank Name</th>
                    <th>Image</th>
                    <th>Charge</th>
                    <th>CardType</th>
                    <th>Action</th>
                   

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@Html.DisplayFor(model => item.Name)</td>
                    <td><img class="img-responsive" src="@item.Image" alt="sala image aayena" height="50" width="50" style="border-radius:50%" /></td>
                    <td>@Html.DisplayFor(model => item.Charge)</td>
                    <td>@Html.DisplayFor(model => item.CardType)</td>
                    
                    <td>
                        <a href="/Bank/EditBank?id=@item.BankId"><i class="fa fa-pencil-square-o" aria-hidden="true" style="color:green;margin:5px; "></i>edit</a>|
                        <a href="/Bank/DeleteBank?id=@item.BankId"><i class="fa fa-trash-o" aria-hidden="true" style="color:red; margin:5px;"></i>delete</a>
                    </td>
                </tr>

                }
            </tbody>
        </table>
    </div>
</section>
<script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tbody tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

BankCharge/Views/Bank/New.cshtml
@model BankCharge.Models.Bank
@{
    ViewData["Title"] = "New";
}


<section class="content-header">
    <section>
        <h3>Add Bank</h3>
        <div class="container">
            <form>
                <table class="table table-responsive  small-text box-default " id="tb" cellpadding="1" cellspacing="1">
                    <tr class="tr-header table-responsive">
                        <th>Bank Name</th>
                        <th>Image</th>
                        <th>Charge</th>
                        <th>Card Type</th>
                        <th>Patner Bank</th>
                        <th><a href="javascript:void(0);" style="font-size:18px;" id="addMore" title="Add More Person"><span class="glyphicon glyphicon-plus"></span></a></th>

                    </tr>
                    <tbody>
                        <tr class="myfield">

                            <td><input type="text" id="txtName" name="Name" placeholder="Bank name.."></td>
                            <td> <input type="file" name="ImageUrl" id="img" /></td>
                            <td> <input type="number" name="Charge" min="100" placeholder="100" value="100"> </td>
                            <td>


                                <select class="js-example-basic-multiple" name="CardType" multiple="multiple">
                                    <option value="">Select CardType</option>
                                    <option value="MasterCard">MasterCard</option>
                                    <option value="STC">STC </option>
                                    <option value="Visa">Visa </option>
                                </select>
                            </td>
                            @*<td>
                                    <select required name="Patner" id="patner">
                                        <option value="">Select Panter Bank</option>
                                        @foreach (var item in ViewBag.BankName)
                                        {
                                            <option value="@item.Bank">@item.Bank </option>
                                        }
                                    </select>
                                </td>*@

                            <td><a href='javascript:void(0);' class='remove'><span class='glyphicon glyphicon-remove'></span></a></td>
                        </tr>
                    </tbody>
                </table>

                <div>

                    <br />

                    <input type="button" id="btnSave" value="Save All" />

                </div>
            </form>

        </div>
        <div>
            <a asp-action="Index">Back To Home</a>
        </div>

    </section>
</section>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script>
    //Add Dynamic Row
    $(function () {

        $('#addMore').on('click', function () {

            var data = $("#tb tr:eq(1)").clone(true).appendTo("#tb");
            data.find("input").val('');

        });
        $(document).on('click', '.remove', function () {
            var trIndex = $(this).closest("tr").index();
            if (trIndex > 1) {
                $(this).closest("tr").remove();
            } else {
                alert("Sorry!! Can't remove first row!");
            }
        });
    });

    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });

    $("body").on("click", "#btnSave", function () {
        
        var formData = new FormData();
        $("#tb tbody").find("tr.myfield").each(function (index) {
            formData.append("banks[" + index + "].Name", $(this).find("td:eq(0)").find("input").val());
            formData.append("banks[" + index + "].ImageUrl", $(this).find("td:eq(1)").find("input[name='ImageUrl']")[0].files[0]);
            formData.append("banks[" + index + "].Charge", $(this).find("td:eq(2)").find("input").val());
            formData.append("banks[" + index + "].CardType", $(this).find("td:eq(3)").find("select").val());
        });
        $.ajax({
            type: "POST",
            url: "/Bank/New",
            data: formData,
            processData: false,
            contentType: false,
            success: function (r) {
                window.location.href = "/Bank/Index";
            }
        });
    });


</script>